#!/bin/bash
set -euo pipefail

DATE=$(date -uI)

O=o$DATE
BKFORMAT=0

mkdir -p $O/v$BKFORMAT

./blocklistmaker -s keyrepos/debianopenssl -d $O/out-debianssl-1 1
./blocklistmaker -s keyrepos/keypairvuln -d $O/out-keypair-2 2
./blocklistmaker -s keyrepos/malware/src/ -d $O/out-ransomware-3 3
./blocklistmaker -s keyrepos/kompromat/src/documentation -d $O/out-documentation-4 4
./blocklistmaker -s keyrepos/kompromat/src/firmware -d $O/out-firmware-5 5
./blocklistmaker -s keyrepos/kompromat/src/localhostcert -d $O/out-localhostcert-6 6
./blocklistmaker -s keyrepos/kompromat/src/localroot -d $O/out-localroot-7 7
./blocklistmaker -s keyrepos/kompromat/src/misc -d $O/out-misc-8 8
./blocklistmaker -s keyrepos/kompromat/src/rfc -d $O/out-rfc-9 9
./blocklistmaker -s keyrepos/kompromat/src/softwaretests -d $O/out-softwaretests-10 10
./blocklistmaker -s keyrepos/kompromat/src/testvectors -d $O/out-testvectors-11 11
./blocklistmaker -s keyrepos/morekeys/web -d $O/out-webkeys-12 12
./blocklistmaker -s keyrepos/gitkeys -d $O/out-gitkeys-13 13

if [ -e new ]; then
	./blocklistmaker -s new -d $O/out-new-99 99
	rm $O/out-new-99/*-long.txt
fi

cat $O/out-*/*-long.txt >"$O/_bklookup_unsorted.txt"
cat $O/out-*/*-short.txt >"$O/_blunsorted.txt"
LC_ALL=C sort -u "$O/_bklookup_unsorted.txt" >"$O/_bklookup_sorted.txt"
LC_ALL=C sort -u "$O/_blunsorted.txt" >"$O/_blsorted.txt"

# badkeys will produce errors if we have duplicates,
# so we make sure we only have the 1st of each hash
cut -c1-16 $O/_bklookup_sorted.txt | uniq -c |
	grep -v " 1 " | sed -e 's:.* ::g' \
	>$O/_duplicates.txt

lfiles=$(for x in $(seq 1 11); do ls $O/out-*-$x/*-long.txt; done)

for dup in $(cat $O/_duplicates.txt); do
	grep -h $dup $lfiles | tail -n +2 >>$O/_lu_exclude.txt
	look $dup $O/_blsorted.txt | tail -n +2 >>$O/_bl_exclude.txt
done

comm -3 "$O/_bklookup_sorted.txt" <(sort $O/_lu_exclude.txt) >$O/v$BKFORMAT/lookup.txt
comm -3 "$O/_blsorted.txt" <(sort $O/_bl_exclude.txt) | xxd -r -p >$O/v$BKFORMAT/blocklist.dat

BLOCKLISTSHA256=$(sha256sum $O/v$BKFORMAT/blocklist.dat | cut -d' ' -f1)
LOOKUPSHA256=$(sha256sum $O/v$BKFORMAT/lookup.txt | cut -d' ' -f1)

sed template.badkeysdata.json \
	-e "s:_DATE_:$DATE:g" \
	-e "s:_BLOCKLISTSHA256_:$BLOCKLISTSHA256:g" \
	-e "s:_LOOKUPSHA256_:$LOOKUPSHA256:g" \
	>$O/v$BKFORMAT/badkeysdata.json

xz $O/v$BKFORMAT/blocklist.dat
xz $O/v$BKFORMAT/lookup.txt
